name: Insfrastrucure Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/deploy.yaml'

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    container:
      image: cytopia/terraform-awscli-helm-kubectl:3.9
    env:               
      TF_VAR_gitops_password: ${{ secrets.GITOPS_PASSWORD }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}  

      # - name: Install AWS CLI
      #   run: |
      #     apk add --no-cache python3 py3-pip groff less
      #     pip3 install awscli      

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # - name: Setup kubectl
      #   uses: azure/setup-kubectl@v4
      #   with:
      #     version:  v1.33.0  
      
      - name: Debug AWS identity
        run: aws sts get-caller-identity

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_DEFAULT_REGION \
            --name online-boutique-eks \

      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f online-boutique-argo-app.yaml -n argocd

      - name: Wait 10 minutes
        run: sleep 900

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

