name: Infrastructure Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  terraform_destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    container:
      image: korgala/aws_helm_terra
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:               
      TF_VAR_gitops_password: ${{ secrets.GITOPS_PASSWORD }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Pre-cleanup Kubernetes Resources
        run: |
          echo "Updating kubeconfig..."
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name online-boutique-eks || true
          
          echo "Deleting ArgoCD applications..."
          kubectl delete applications --all -n argocd --timeout=5m || true
          
          echo "Deleting ExternalSecrets..."
          kubectl delete externalsecrets --all -A --timeout=5m || true
          
          echo "Waiting for finalizers to clear..."
          sleep 30

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        timeout-minutes: 30

      - name: Verify Destruction
        if: always()
        run: |
          echo "Checking for remaining resources..."
          aws eks list-clusters --region $AWS_DEFAULT_REGION || echo "EKS cleanup complete"